const repo = "https://github.com/johnzertuche/cargo-ai";

const hosts = [
  ["Claude", "/brand-claude.svg"],
  ["Cursor", "/brand-cursor.svg"],
  ["Codex", null],
];

export default function Home() {
  return <main>
    <nav className="nav"><a className="brand" href="#top" aria-label="Cargo home"><Mark />CARGO</a><div><a href="#product">Product</a><a href="#security">Security</a><a href="#open">Open source</a></div><a className="nav-cta" href={repo}>View on GitHub <span>↗</span></a></nav>
    <section className="hero" id="top"><div className="hero-copy"><p className="kicker"><i />LOCAL-FIRST AI PORTABILITY</p><h1>Your AI life.<br /><em>Owned by you.</em></h1><p className="lede">Carry your MCP connections, preferences, and memory between Claude, Cursor, and Codex—without handing a hosted company your vault.</p><div className="actions"><a className="primary" href={`${repo}#desktop-app`}>Get the desktop app <span>→</span></a><a href={repo}>Explore the source</a></div><div className="principles"><span>Accountless by default</span><span>Encrypted on device</span><span>Every change previewed</span></div></div><Network /></section>
    <section className="manifesto"><p>AI should be interchangeable.<br />Your context should not be.</p><span>Cargo is an open, local control plane that lets you move without starting over.</span></section>
    <section className="product" id="product"><header><p>01 / HOW IT WORKS</p><h2>Move your setup.<br />Keep the keys.</h2><span>Cargo discovers documented local configuration, normalizes credential-free definitions, and stores them inside an encrypted vault protected by your operating system.</span></header><div className="steps"><article><b>01</b><div className="step-visual discover"><i /><i /><i /></div><h3>Discover</h3><p>Find supported AI clients without reading their credential stores.</p></article><article><b>02</b><div className="step-visual vault"><Mark /></div><h3>Carry</h3><p>Keep connections and memory in a device-owned encrypted vault.</p></article><article><b>03</b><div className="step-visual review"><i /><i /><strong>✓</strong></div><h3>Review</h3><p>See the target, fingerprints, and warnings before any write occurs.</p></article><article><b>04</b><div className="step-visual remove"><i /><strong>×</strong></div><h3>Remove safely</h3><p>Delete only what Cargo installed. Drift stops removal instead of erasing edits.</p></article></div></section>
    <section className="security" id="security"><div className="security-visual"><div className="rings"><i /><i /><i /><Mark /></div><p>NO HOSTED VAULT<br />NO OPERATOR BACKDOOR</p></div><div className="security-copy"><p>02 / SECURITY MODEL</p><h2>Your device is<br />the boundary.</h2><p>There is no Cargo account server in the trust path. Your profile, connection definitions, memory, deployment ownership, and receipts are encrypted locally.</p><ul><li><b>OS-protected key</b><span>The vault key is kept in macOS Keychain, separate from the encrypted database.</span></li><li><b>Authenticated records</b><span>Each record uses XChaCha20-Poly1305 with a unique nonce and authenticated identity.</span></li><li><b>Transactional changes</b><span>Host writes are fingerprint checked, atomic, verified, and automatically restored on verification failure.</span></li><li><b>Honest removal</b><span>The preview removes only managed host configuration and explicitly does not claim provider revocation.</span></li></ul></div></section>
    <section className="portable"><header><p>03 / PORTABLE BY CHOICE</p><h2>Two ways out.<br />Neither locks you in.</h2></header><div><article><span>PORTABLE PACK / JSON</span><h3>Share the map.</h3><p>Explicitly selected connection definitions and memory. Credential values and device paths are excluded, and every import is previewed before merge.</p><code>contains credential values / no</code></article><article className="dark"><span>ENCRYPTED PACK / AGE</span><h3>Protect the transfer.</h3><p>The same selected records, encrypted with a passphrase before writing. It excludes credentials, receipts, deployments, and the vault key.</p><code>full vault recovery / no</code></article></div></section>
    <section className="open" id="open"><div><p>04 / OPEN BY DESIGN</p><h2>Trust the code.<br />Not the company.</h2></div><div className="open-copy"><p>The core, desktop application, schemas, threat model, and adapter tests live in public. Self-host, fork, audit, or leave. The format is the product—not a walled garden.</p><dl><div><dt>License</dt><dd>Apache 2.0</dd></div><div><dt>Cloud account</dt><dd>Not required</dd></div><div><dt>Telemetry</dt><dd>None by default</dd></div><div><dt>Credential custody</dt><dd>Your device</dd></div></dl><a className="primary" href={repo}>Open the repository <span>↗</span></a></div></section>
    <section className="hosts-band"><p>DOCUMENTED SURFACES IN THE PRIVATE PREVIEW</p><div>{hosts.map(([name, icon]) => <span key={name}>{icon ? <img src={icon} alt="" /> : <i>◎</i>}{name}</span>)}</div><small>Additional adapters ship only after conformance and revocation tests pass.</small></section>
    <section className="cta"><Mark /><p>YOUR TOOLS. YOUR MEMORY. YOUR EXIT.</p><h2>Take your AI life with you.</h2><div className="actions"><a className="primary" href={`${repo}#desktop-app`}>Get Cargo <span>→</span></a><a href={`${repo}/blob/main/SECURITY.md`}>Read the security model</a></div></section>
    <footer><a className="brand" href="#top"><Mark />CARGO</a><p>Open-source AI portability infrastructure.</p><span>Private preview · 2026</span></footer>
  </main>;
}

function Mark() { return <span className="mark" aria-hidden="true"><i /><b /></span>; }

function Network() {
  return <div className="network" aria-label="Cargo connects portable local context to supported AI clients"><i className="orbit one" /><i className="orbit two" /><i className="line l1" /><i className="line l2" /><i className="line l3" /><div className="core"><Mark /><strong>LOCAL VAULT</strong><small>DEVICE OWNED</small></div>{hosts.map(([name, icon], index) => <div className={`node n${index + 1}`} key={name}>{icon ? <img src={icon} alt="" /> : <i>◎</i>}<span>{name}</span><b>LOCAL</b></div>)}</div>;
}
